# Generated by Django 4.2.13 on 2024-07-10 03:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZonasHomogeneas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.IntegerField(null=True)),
                ('codigo_zon', models.CharField(max_length=50, null=True)),
                ('nombre_zon', models.CharField(max_length=50, null=True)),
                ('valor', models.FloatField(null=True)),
                ('shape_length', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
