# Generated by Django 4.2.13 on 2024-07-10 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=254, null=True)),
                ('num_dist', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
